### ISSUE TITLE
Expired Account Should not be able to login

### ISSUE THREAD

**Issue by omnitekinc** [grahamjleach/aeraedu#60]
Accounts that have been expired should not be able to login. When they tried to login it should say:

Your account has been expired, please content AERA for details.
AERA
Ph: 888-326-2372 or 815-526-7600
karen@aera.org

**Comment by grahamjleach** [comment]
done

**Comment by omnitekinc** [comment]
Now if I update the account to not expired, the user still can't login. 
Larry Adair
ladair
LzGMifK
